import type { Metadata } from "next";
import { Open_Sans, IBM_Plex_Mono } from "next/font/google";
import { LoadingWrapper } from "./LoadingWrapper";
import "./globals.css";

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
  weight: "400",
});

const ibmPlexMono = IBM_Plex_Mono({
  variable: "--font-ibm-plex-mono",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="preload"
          href="https://trritavoaewykjuyzjty.supabase.co/storage/v1/object/public/quiz-media/logo_no_back.png"
          as="image"
          type="image/png"
        />
        <link
          rel="preload"
          href="https://trritavoaewykjuyzjty.supabase.co/storage/v1/object/public/quiz-media/home.png"
          as="image"
          type="image/png"
        />
      </head>
      <body className={`${openSans.variable} ${ibmPlexMono.variable}`}>
        <LoadingWrapper>{children}</LoadingWrapper>
      </body>
    </html>
  );
}
